### ISSUE TITLE
unrecognized argument

### ISSUE THREAD

**Issue by lghasemzadeh** [vbsinha/fuzzy-image-enhancement#3]

**Comment by vbsinha** [comment]
I am assuming from your editing history that you have understood that stuff in square parentheses are optional arguments. If you want to pass them, remove the square brackets. Good luck!

**Comment by lghasemzadeh** [comment]
@vbsinha yes thank you very much :)
İ just added a gray scale (256*256) to the original folder, ı applied noise on it and then used filters. but the result was not the thing that I was looking for. I think because the image that I added to original folder was noisy by itself.
so I directly added my image to noisy folder and gave the same images (as original and noisy) to the filter application, and the result got strange.

Actually I have noisy (or I can say low quality image) I want to just apply those different filters and see the result. I want to skip the step related to adding noise to the image.
Is it possible?

I appreciate if you help

**Comment by vbsinha** [comment]
You can run the command:
`python main.py --image NOISYIMGPATH --method METHOD`
This will read the noisy image and run the filter mentioned in method parameter. The output will be stored in `enhanced` directory.
